### ISSUE TITLE
Isolate Row Module 관련 질문.

### ISSUE THREAD

**Issue by dasebee** [yamoo9/FDS#56]
선생님!!
오늘 수업때 작성하신 코드에서  `$ii: $i - 1;`는 왜 들어가는 건가요?ㅜㅜ??
```   css
  @for $i from 1 through $columns {
   @if $i > 1 {
    $ii: $i - 1;
    .is-isolate > .order-#{$ii},
    .is-isolate > .o-#{$ii} {
      margin-left: order-width($ii);
    }
}
```
 $ii: $i - 1; 때문에 .order-11까지 밖에 클래스가 만들어지지 않는 것 같은데 생략하고 아래 처럼 쓰면 안되나요???
``` css
@for $i from 1 through $columns {
        .is-isolate > .order-#{$i},
        .is-isolate > .o-#{$i} {
        margin-left: order-width($i);}
  }
```

**Comment by yamoo9** [comment]
네~ 됩니다 ^ㅡ^ 그 자리에서 즉석으로 코드를 짜다 보면 여러 생각을 하게 되는데
이후 코드 리뷰를 통해 문제를 다시 보게 되면 보다 나은 방법을 찾게 되죠!
어제 수업 때 짰던 코드는 너무 많은 생각을 한 듯~

아래 처럼 수정하면 되겠네요! ^ㅡ^ 짝!짝!짝!
감사합니다~

```scss
// Isolate Row Module
// 격리된 로우(행) 모듈 -> 컬럼에 설정
.is-isolate > .order-#{$i},
.is-isolate > .o-#{$i} {
  margin-left: order-width($i);
}
```
